name: Telegram Music Downloader

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 0 * * *" # optional: run daily

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Telegram music downloader
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
        TELEGRAM_PASSWORD: ${{ secrets.TELEGRAM_PASSWORD }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      run: |
        mkdir output
        python main.py --output output

    - name: Upload downloaded music
      uses: actions/upload-artifact@v4
      with:
        name: telegram-music
        path: output
